---
server:
  port: 8885
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    read:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/inventory_mgmt
      username: root
      password: Welcome@123
    write:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/inventory_mgmt
      username: root
      password: Welcome@123
  jpa:
    show_sql: true
    generate-ddl: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  messages:
    basename: errors
contact-info:
  contactNo: 8888877777
  emailAddress: inventory-dev@gmail.com
...
---
server:
  port: 8887
spring:
  config:
    activate:
      on-profile: test
  datasource:
    read:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/inventory_mgmt_test
      username: root
      password: Welcome@123
    write:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/inventory_mgmt_test
      username: root
      password: Welcome@123
  jpa:
    show_sql: true
    generate-ddl: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  messages:
    basename: errors
contact-info:
  contactNo: 7777788888
  emailAddress: inventory-test@gmail.com
...