---
server:
  port: 8882
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    read:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/inventory_mgmt
      username: root
      password: Welcome@123
    write:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/inventory_mgmt
      username: root
      password: Welcome@123
  jpa:
    show-sql: true
    generate-ddl: false
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQLDialect
  management:
    endpoints:
      web:
        exposure:
          include: health,info
    endpoint:
      health:
        show-details: always
        enabled: true
      info:
        env:
          enabled: true
  messages:
    baseName: errors
contact-info:
  contactNo: 7777788888
  emailAddress: dev@gmail.com
eureka:
  client:
    register-with-eureka: true
    fetch-registry: false
    service-url:
      defaultZone: "http://localhost:9988/eureka,http://localhost:9999/eureka"
---
server:
  port: 8884
spring:
  config:
    activate:
      on-profile: test
  datasource:
    read:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/inventory_mgmt_test
      username: root
      password: Welcome@123
    write:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/inventory_mgmt_test
      username: root
      password: Welcome@123
  jpa:
    show-sql: true
    generate-ddl: false
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQLDialect
  management:
    endpoints:
      web:
        exposure:
          include:
            - health
            - info
    endpoint:
      health:
        enabled: true
        show-details: true
      info:
        env:
          enabled: true
  messages:
    basename: errors
contact-info:
  contactNo: 8888899999
  emailAddress: test@gmail.com
eureka:
  client:
    register-with-eureka: true
    fetch-registry: false
    service-url:
      defaultZone: "http://localhost:9988/eureka,http://localhost:9999/eureka"